# Generated by Django 5.1.4 on 2024-12-07 02:53

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('RE', 'Responded'), ('NR', 'No Response')], default='NR', max_length=2)),
                ('slug', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghjkmnprstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789', length=10, max_length=10, prefix='', unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('GO', 'Going'), ('NG', 'Not Going'), ('NR', 'No Response')], default='NR', max_length=2)),
                ('dietary_restrictions', models.TextField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guests', to='guests.guestgroup')),
            ],
        ),
    ]
