# Generated by Django 5.1.4 on 2024-12-07 04:13

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guestgroup',
            name='slug',
        ),
        migrations.CreateModel(
            name='GuestGroupEmailInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghjkmnprstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789', length=10, max_length=10, prefix='', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='invitations', to='guests.guestgroup')),
            ],
        ),
    ]
