# Generated by Django 5.1.4 on 2024-12-07 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0002_remove_guestgroup_slug_guestgroupemailinvitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestgroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
