# Generated by Django 5.1.4 on 2024-12-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0004_guestgroup_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='dietary_restrictions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
